/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as AuthenticatedQuizTopicDifficultyRouteImport } from './routes/_authenticated/quiz.$topic.$difficulty'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuizTopicDifficultyRoute =
  AuthenticatedQuizTopicDifficultyRouteImport.update({
    id: '/quiz/$topic/$difficulty',
    path: '/quiz/$topic/$difficulty',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/quiz/$topic/$difficulty': typeof AuthenticatedQuizTopicDifficultyRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/quiz/$topic/$difficulty': typeof AuthenticatedQuizTopicDifficultyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/_authenticated/quiz/$topic/$difficulty': typeof AuthenticatedQuizTopicDifficultyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/practice'
    | '/api/public/bootstrap-admin'
    | '/quiz/$topic/$difficulty'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/practice'
    | '/'
    | '/api/public/bootstrap-admin'
    | '/quiz/$topic/$difficulty'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/practice'
    | '/_authenticated/'
    | '/api/public/bootstrap-admin'
    | '/_authenticated/quiz/$topic/$difficulty'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quiz/$topic/$difficulty': {
      id: '/_authenticated/quiz/$topic/$difficulty'
      path: '/quiz/$topic/$difficulty'
      fullPath: '/quiz/$topic/$difficulty'
      preLoaderRoute: typeof AuthenticatedQuizTopicDifficultyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedQuizTopicDifficultyRoute: typeof AuthenticatedQuizTopicDifficultyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedQuizTopicDifficultyRoute: AuthenticatedQuizTopicDifficultyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
