/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users.$userId'
import { Route as AuthenticatedQuizTopicDifficultyRouteImport } from './routes/_authenticated/quiz.$topic.$difficulty'
import { Route as AuthenticatedQuizTopicDifficultyResultSessionIdRouteImport } from './routes/_authenticated/quiz.$topic.$difficulty.result.$sessionId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedQuizTopicDifficultyRoute =
  AuthenticatedQuizTopicDifficultyRouteImport.update({
    id: '/quiz/$topic/$difficulty',
    path: '/quiz/$topic/$difficulty',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuizTopicDifficultyResultSessionIdRoute =
  AuthenticatedQuizTopicDifficultyResultSessionIdRouteImport.update({
    id: '/result/$sessionId',
    path: '/result/$sessionId',
    getParentRoute: () => AuthenticatedQuizTopicDifficultyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/quiz/$topic/$difficulty': typeof AuthenticatedQuizTopicDifficultyRouteWithChildren
  '/quiz/$topic/$difficulty/result/$sessionId': typeof AuthenticatedQuizTopicDifficultyResultSessionIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/quiz/$topic/$difficulty': typeof AuthenticatedQuizTopicDifficultyRouteWithChildren
  '/quiz/$topic/$difficulty/result/$sessionId': typeof AuthenticatedQuizTopicDifficultyResultSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/_authenticated/quiz/$topic/$difficulty': typeof AuthenticatedQuizTopicDifficultyRouteWithChildren
  '/_authenticated/quiz/$topic/$difficulty/result/$sessionId': typeof AuthenticatedQuizTopicDifficultyResultSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/performance'
    | '/practice'
    | '/users'
    | '/users/$userId'
    | '/api/public/bootstrap-admin'
    | '/quiz/$topic/$difficulty'
    | '/quiz/$topic/$difficulty/result/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/performance'
    | '/practice'
    | '/users'
    | '/'
    | '/users/$userId'
    | '/api/public/bootstrap-admin'
    | '/quiz/$topic/$difficulty'
    | '/quiz/$topic/$difficulty/result/$sessionId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/performance'
    | '/_authenticated/practice'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/users/$userId'
    | '/api/public/bootstrap-admin'
    | '/_authenticated/quiz/$topic/$difficulty'
    | '/_authenticated/quiz/$topic/$difficulty/result/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/quiz/$topic/$difficulty': {
      id: '/_authenticated/quiz/$topic/$difficulty'
      path: '/quiz/$topic/$difficulty'
      fullPath: '/quiz/$topic/$difficulty'
      preLoaderRoute: typeof AuthenticatedQuizTopicDifficultyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz/$topic/$difficulty/result/$sessionId': {
      id: '/_authenticated/quiz/$topic/$difficulty/result/$sessionId'
      path: '/result/$sessionId'
      fullPath: '/quiz/$topic/$difficulty/result/$sessionId'
      preLoaderRoute: typeof AuthenticatedQuizTopicDifficultyResultSessionIdRouteImport
      parentRoute: typeof AuthenticatedQuizTopicDifficultyRoute
    }
  }
}

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedQuizTopicDifficultyRouteChildren {
  AuthenticatedQuizTopicDifficultyResultSessionIdRoute: typeof AuthenticatedQuizTopicDifficultyResultSessionIdRoute
}

const AuthenticatedQuizTopicDifficultyRouteChildren: AuthenticatedQuizTopicDifficultyRouteChildren =
  {
    AuthenticatedQuizTopicDifficultyResultSessionIdRoute:
      AuthenticatedQuizTopicDifficultyResultSessionIdRoute,
  }

const AuthenticatedQuizTopicDifficultyRouteWithChildren =
  AuthenticatedQuizTopicDifficultyRoute._addFileChildren(
    AuthenticatedQuizTopicDifficultyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedQuizTopicDifficultyRoute: typeof AuthenticatedQuizTopicDifficultyRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedQuizTopicDifficultyRoute:
    AuthenticatedQuizTopicDifficultyRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
